//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EShop.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class ListAnswerName
    {
        //таблица ответов
        public int idLA { get; set; }
        public int idQ { get; set; }
        [Required]
        [Display(Name = "Текст ответа")]
        public string NameAnswer { get; set; }
        public bool Right { get; set; }
    
        public virtual QuestionName QuestionName { get; set; }
    }
}
