//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EShop.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;
    public partial class QuestionName
    {
        //таблица вопросов
        public QuestionName()
        {
            this.ListAnswerName = new HashSet<ListAnswerName>();
        }
    
        public int idQ { get; set; }
        public int idTest { get; set; }
        [Required]
        [Display(Name = "Текст вопроса")]
        public string NameQ { get; set; }
        public int? NextQ { get; set; }
        
        public virtual ICollection<ListAnswerName> ListAnswerName { get; set; }
        public virtual TestName TestName { get; set; }
    }
}
