//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EShop.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;
    public partial class TestName
    {
        //таблица тестов
        public TestName()
        {
            this.QuestionName = new HashSet<QuestionName>();
            this.UserTest = new HashSet<UserTest>();
        }
        
        public int idTest { get; set; }
        [Display(Name="Название теста")]
        [Required] 
        public string NameTest { get; set; }
        [Required]
        [Display(Name = "Время на тест (в минутах)")]
        public int TimeOnTest{ get; set; }
        [Required]
        [Display(Name = "Описание теста")]
        public string AboutTest { get; set; }

        public virtual ICollection<QuestionName> QuestionName { get; set; }
        public virtual ICollection<UserTest> UserTest { get; set; }
    }
}
