//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EShop.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web.Mvc;
    public partial class UserTest
    {
        //результаты тестов пользователей
        public UserTest()
        {
            this.UserAnswerTest = new HashSet<UserAnswerTest>();
        }
    
        public int idUserTest { get; set; }
        public int idTest { get; set; }
        public string UserName { get; set; }
        public decimal? Result { get; set; }
        public virtual TestName TestName { get; set; }
        public virtual ICollection<UserAnswerTest> UserAnswerTest { get; set; }
    }
}
