//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAnswerTest
    {
        //ответы пользователей
        public int idUserAnswer { get; set; }
        public int idUserTest { get; set; }
        public int idQ { get; set; }
        public int idLA { get; set; }
        public Nullable<int> RightA { get; set; }
    
        public virtual UserTest UserTest { get; set; }
    }
}
